apiVersion: v1
kind: Service
metadata:
  name: {{ include "java-app.fullname" . }}
  labels:
    {{- include "java-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      {{- if .Values.nodePort }}
      nodePort: {{ .Values.nodePort | int }}
      {{- end }}
      protocol: TCP
      name: http
    {{- if .Values.debugPort }}
    - port: {{ .Values.debugPort | int }}
      targetPort: {{ .Values.containerDebugPort | int }}
      nodePort: {{ .Values.debugPort | int }}
      protocol: TCP
      name: debugport
    {{- end }}
    {{ if .Values.jmxJolokiaPrometheusExporter.enabled }}
    - name: exporter
      protocol: TCP
      port: {{ .Values.jmxJolokiaPrometheusExporter.port }}
      targetPort: exporter
    {{ end }}
  selector:
    {{- include "java-app.selectorLabels" . | nindent 4 }}
